Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: Dora Runtime raised an error.

Caused by:
   0: main task failed
   1: operator judge-agent/op raised an error
   2: error in Python module at /home/mofaDora/mofa/python/examples/agentfight1/scripts/judge_agent.py
   3: Traceback (most recent call last):
        File "/home/mofaDora/mofa/python/examples/agentfight1/scripts/judge_agent.py", line 24, in on_event
          inputs = load_agent_config(yaml_file_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/mofaDora/mofa/python/mofa/kernel/utils/util.py", line 15, in load_agent_config
          params = read_yaml(yaml_file)
                   ^^^^^^^^^^^^^^^^^^^^
        File "/home/mofaDora/mofa/python/mofa/utils/files/read.py", line 13, in read_yaml
          with open(file_path, 'r') as file:
               ^^^^^^^^^^^^^^^^^^^^

      FileNotFoundError: [Errno 2] No such file or directory: '/home/mofaDora/mofa/python/examples/agentfight1/scripts/configs/judge_agent.yml'

Location:
    binaries/runtime/src/operator/python.rs:28:9
